"""
Seed de prefijos de indicativos de radioaficionados.
Fuente: ITU / ARRL prefix list.
Solo se ejecuta si la tabla está vacía.
"""
from sqlalchemy.orm import Session
from app import models

# (prefijo, país, zona_codigo)
# zona_codigo se asigna para zonas mexicanas; NULL = estación extranjera
PREFIJOS: list[tuple[str, str, str | None]] = [
    # ─── México ──────────────────────────────────────────────────────────────
    ("XE1", "México", "XE1"),
    ("XE2", "México", "XE2"),
    ("XE3", "México", "XE3"),
    ("XE4", "México", "XE4"),
    ("XE5", "México", "XE5"),
    ("XE",  "México", None),
    ("XF1", "México", "XF1"),
    ("XF2", "México", "XF2"),
    ("XF3", "México", "XF3"),
    ("XF4", "México", "XF4"),
    ("XF5", "México", None),
    ("XF",  "México", None),
    ("4A",  "México", None),
    ("4B",  "México", None),
    ("6D",  "México", None),
    ("6E",  "México", None),
    # ─── Estados Unidos ───────────────────────────────────────────────────────
    ("KH6", "Estados Unidos (Hawái)", None),
    ("KL",  "Estados Unidos (Alaska)", None),
    ("KP4", "Puerto Rico (EUA)", None),
    ("KP2", "Islas Vírgenes (EUA)", None),
    ("KG4", "Guantánamo (EUA)", None),
    ("KH0", "Islas Marianas (EUA)", None),
    ("KH2", "Guam (EUA)", None),
    ("KH8", "Samoa Americana (EUA)", None),
    ("KH",  "Estados Unidos (Pacífico)", None),
    ("KP",  "Estados Unidos (Caribe)", None),
    ("AA",  "Estados Unidos", None),
    ("AB",  "Estados Unidos", None),
    ("AC",  "Estados Unidos", None),
    ("AD",  "Estados Unidos", None),
    ("AE",  "Estados Unidos", None),
    ("AF",  "Estados Unidos", None),
    ("AG",  "Estados Unidos", None),
    ("AH",  "Estados Unidos", None),
    ("AI",  "Estados Unidos", None),
    ("AJ",  "Estados Unidos", None),
    ("AK",  "Estados Unidos", None),
    ("AL",  "Estados Unidos", None),
    ("W",   "Estados Unidos", None),
    ("K",   "Estados Unidos", None),
    ("N",   "Estados Unidos", None),
    # ─── Canadá ───────────────────────────────────────────────────────────────
    ("VA",  "Canadá", None),
    ("VB",  "Canadá", None),
    ("VC",  "Canadá", None),
    ("VD",  "Canadá", None),
    ("VE",  "Canadá", None),
    ("VF",  "Canadá", None),
    ("VG",  "Canadá", None),
    ("VO",  "Canadá", None),
    ("VY",  "Canadá", None),
    # ─── América Central ──────────────────────────────────────────────────────
    ("TG",  "Guatemala", None),
    ("TI",  "Costa Rica", None),
    ("TE",  "Costa Rica", None),
    ("YN",  "Nicaragua", None),
    ("H6",  "Nicaragua", None),
    ("H7",  "Nicaragua", None),
    ("HR",  "Honduras", None),
    ("YS",  "El Salvador", None),
    ("HU",  "El Salvador", None),
    ("HP",  "Panamá", None),
    # ─── Caribe ───────────────────────────────────────────────────────────────
    ("HH",  "Haití", None),
    ("HI",  "República Dominicana", None),
    ("CO",  "Cuba", None),
    ("CM",  "Cuba", None),
    ("CL",  "Cuba", None),
    ("T4",  "Cuba", None),
    ("J3",  "Granada", None),
    ("J6",  "Santa Lucía", None),
    ("J7",  "Dominica", None),
    ("J8",  "San Vicente y las Granadinas", None),
    ("VP9", "Bermuda", None),
    ("V2",  "Antigua y Barbuda", None),
    ("V4",  "San Cristóbal y Nieves", None),
    ("ZF",  "Islas Caimán", None),
    ("6Y",  "Jamaica", None),
    ("8P",  "Barbados", None),
    ("FG",  "Guadalupe (Francia)", None),
    ("FM",  "Martinica (Francia)", None),
    ("FJ",  "San Bartolomé (Francia)", None),
    ("VP2E","Anguila (RU)", None),
    ("VP2M","Montserrat (RU)", None),
    ("VP5", "Islas Turcas y Caicos (RU)", None),
    ("P4",  "Aruba", None),
    ("PJ",  "Antillas Neerlandesas", None),
    ("PZ",  "Surinam", None),
    ("9Y",  "Trinidad y Tobago", None),
    # ─── América del Sur ──────────────────────────────────────────────────────
    ("YV",  "Venezuela", None),
    ("YX",  "Venezuela", None),
    ("4M",  "Venezuela", None),
    ("PP",  "Brasil", None),
    ("PQ",  "Brasil", None),
    ("PR",  "Brasil", None),
    ("PS",  "Brasil", None),
    ("PT",  "Brasil", None),
    ("PU",  "Brasil", None),
    ("PV",  "Brasil", None),
    ("PW",  "Brasil", None),
    ("PX",  "Brasil", None),
    ("PY",  "Brasil", None),
    ("ZV",  "Brasil", None),
    ("ZW",  "Brasil", None),
    ("ZX",  "Brasil", None),
    ("ZY",  "Brasil", None),
    ("ZZ",  "Brasil", None),
    ("LU",  "Argentina", None),
    ("LO",  "Argentina", None),
    ("LP",  "Argentina", None),
    ("LQ",  "Argentina", None),
    ("LR",  "Argentina", None),
    ("LS",  "Argentina", None),
    ("LT",  "Argentina", None),
    ("LV",  "Argentina", None),
    ("LW",  "Argentina", None),
    ("AY",  "Argentina", None),
    ("AZ",  "Argentina", None),
    ("CE",  "Chile", None),
    ("CA",  "Chile", None),
    ("CB",  "Chile", None),
    ("CC",  "Chile", None),
    ("CD",  "Chile", None),
    ("XQ",  "Chile", None),
    ("XR",  "Chile", None),
    ("HC",  "Ecuador", None),
    ("HD",  "Ecuador", None),
    ("OA",  "Perú", None),
    ("OB",  "Perú", None),
    ("OC",  "Perú", None),
    ("CP",  "Bolivia", None),
    ("ZP",  "Paraguay", None),
    ("CX",  "Uruguay", None),
    ("CV",  "Uruguay", None),
    ("HJ",  "Colombia", None),
    ("HK",  "Colombia", None),
    ("5J",  "Colombia", None),
    ("5K",  "Colombia", None),
    # ─── Europa ───────────────────────────────────────────────────────────────
    ("GD",  "Isla de Man (RU)", None),
    ("GI",  "Irlanda del Norte (RU)", None),
    ("GJ",  "Jersey (RU)", None),
    ("GM",  "Escocia (RU)", None),
    ("GU",  "Guernsey (RU)", None),
    ("GW",  "Gales (RU)", None),
    ("G",   "Reino Unido", None),
    ("M",   "Reino Unido", None),
    ("2E",  "Reino Unido", None),
    ("EI",  "Irlanda", None),
    ("EJ",  "Irlanda", None),
    ("F",   "Francia", None),
    ("TM",  "Francia", None),
    ("TK",  "Córcega (Francia)", None),
    ("IT9", "Sicilia (Italia)", None),
    ("IS0", "Cerdeña (Italia)", None),
    ("IK",  "Italia", None),
    ("IW",  "Italia", None),
    ("IZ",  "Italia", None),
    ("IU",  "Italia", None),
    ("I",   "Italia", None),
    ("DL",  "Alemania", None),
    ("DA",  "Alemania", None),
    ("DB",  "Alemania", None),
    ("DC",  "Alemania", None),
    ("DD",  "Alemania", None),
    ("DE",  "Alemania", None),
    ("DF",  "Alemania", None),
    ("DG",  "Alemania", None),
    ("DH",  "Alemania", None),
    ("DJ",  "Alemania", None),
    ("DK",  "Alemania", None),
    ("DM",  "Alemania", None),
    ("DN",  "Alemania", None),
    ("DO",  "Alemania", None),
    ("DP",  "Alemania", None),
    ("DQ",  "Alemania", None),
    ("DR",  "Alemania", None),
    ("EA8", "España (Islas Canarias)", None),
    ("EA9", "España (Ceuta/Melilla)", None),
    ("EA",  "España", None),
    ("EB",  "España", None),
    ("EC",  "España", None),
    ("ED",  "España", None),
    ("EE",  "España", None),
    ("EF",  "España", None),
    ("EG",  "España", None),
    ("EH",  "España", None),
    ("CT3", "Madeira (Portugal)", None),
    ("CU",  "Azores (Portugal)", None),
    ("CS",  "Portugal", None),
    ("CT",  "Portugal", None),
    ("CQ",  "Portugal", None),
    ("CR",  "Portugal", None),
    ("PA",  "Países Bajos", None),
    ("PB",  "Países Bajos", None),
    ("PC",  "Países Bajos", None),
    ("PD",  "Países Bajos", None),
    ("PE",  "Países Bajos", None),
    ("PH",  "Países Bajos", None),
    ("PI",  "Países Bajos", None),
    ("ON",  "Bélgica", None),
    ("OO",  "Bélgica", None),
    ("OP",  "Bélgica", None),
    ("OT",  "Bélgica", None),
    ("OZ",  "Dinamarca", None),
    ("OX",  "Groenlandia (Dinamarca)", None),
    ("OY",  "Islas Feroe (Dinamarca)", None),
    ("SM",  "Suecia", None),
    ("SA",  "Suecia", None),
    ("SK",  "Suecia", None),
    ("SL",  "Suecia", None),
    ("8S",  "Suecia", None),
    ("OH",  "Finlandia", None),
    ("OF",  "Finlandia", None),
    ("OG",  "Finlandia", None),
    ("OI",  "Finlandia", None),
    ("LA",  "Noruega", None),
    ("LB",  "Noruega", None),
    ("LC",  "Noruega", None),
    ("LG",  "Noruega", None),
    ("LN",  "Noruega", None),
    ("JW",  "Svalbard (Noruega)", None),
    ("JX",  "Jan Mayen (Noruega)", None),
    ("TF",  "Islandia", None),
    ("OE",  "Austria", None),
    ("HB9", "Suiza", None),
    ("HB0", "Liechtenstein", None),
    ("HB",  "Suiza", None),
    ("LX",  "Luxemburgo", None),
    ("3A",  "Mónaco", None),
    ("HV",  "Ciudad del Vaticano", None),
    ("T7",  "San Marino", None),
    ("SP",  "Polonia", None),
    ("SQ",  "Polonia", None),
    ("SR",  "Polonia", None),
    ("3Z",  "Polonia", None),
    ("OK",  "República Checa", None),
    ("OL",  "República Checa", None),
    ("OM",  "Eslovaquia", None),
    ("YO",  "Rumanía", None),
    ("YP",  "Rumanía", None),
    ("YQ",  "Rumanía", None),
    ("YR",  "Rumanía", None),
    ("HA",  "Hungría", None),
    ("HG",  "Hungría", None),
    ("LZ",  "Bulgaria", None),
    ("S5",  "Eslovenia", None),
    ("9A",  "Croacia", None),
    ("YU",  "Serbia", None),
    ("YT",  "Serbia", None),
    ("4N",  "Serbia", None),
    ("4O",  "Montenegro", None),
    ("E7",  "Bosnia y Herzegovina", None),
    ("T9",  "Bosnia y Herzegovina", None),
    ("Z3",  "Macedonia del Norte", None),
    ("Z6",  "Kosovo", None),
    ("SV",  "Grecia", None),
    ("SX",  "Grecia", None),
    ("J4",  "Grecia", None),
    ("5B",  "Chipre", None),
    ("P3",  "Chipre", None),
    ("ZB",  "Gibraltar (RU)", None),
    ("UA9", "Rusia (Asiática)", None),
    ("RA9", "Rusia (Asiática)", None),
    ("UA",  "Rusia", None),
    ("RA",  "Rusia", None),
    ("RK",  "Rusia", None),
    ("RL",  "Rusia", None),
    ("RM",  "Rusia", None),
    ("RN",  "Rusia", None),
    ("RO",  "Rusia", None),
    ("RT",  "Rusia", None),
    ("RU",  "Rusia", None),
    ("RV",  "Rusia", None),
    ("RW",  "Rusia", None),
    ("RX",  "Rusia", None),
    ("RY",  "Rusia", None),
    ("RZ",  "Rusia", None),
    ("R",   "Rusia", None),
    ("EW",  "Bielorrusia", None),
    ("UT",  "Ucrania", None),
    ("UW",  "Ucrania", None),
    ("EM",  "Ucrania", None),
    ("EN",  "Ucrania", None),
    ("EO",  "Ucrania", None),
    ("UR",  "Ucrania", None),
    ("LY",  "Lituania", None),
    ("YL",  "Letonia", None),
    ("ES",  "Estonia", None),
    ("UN",  "Kazajistán", None),
    ("UO",  "Kazajistán", None),
    ("UK",  "Uzbekistán", None),
    ("UJ",  "Uzbekistán", None),
    ("EX",  "Kirguistán", None),
    ("EY",  "Tayikistán", None),
    ("EZ",  "Turkmenistán", None),
    ("4J",  "Azerbaiyán", None),
    ("4K",  "Azerbaiyán", None),
    ("4L",  "Georgia", None),
    ("EK",  "Armenia", None),
    ("TA",  "Turquía", None),
    ("TC",  "Turquía", None),
    ("YM",  "Turquía", None),
    # ─── Medio Oriente ────────────────────────────────────────────────────────
    ("OD",  "Líbano", None),
    ("YK",  "Siria", None),
    ("JY",  "Jordania", None),
    ("4X",  "Israel", None),
    ("4Z",  "Israel", None),
    ("YI",  "Irak", None),
    ("EP",  "Irán", None),
    ("EQ",  "Irán", None),
    ("A4",  "Omán", None),
    ("A6",  "Emiratos Árabes Unidos", None),
    ("A7",  "Catar", None),
    ("A9",  "Baréin", None),
    ("HZ",  "Arabia Saudita", None),
    ("7Z",  "Arabia Saudita", None),
    # ─── Asia ─────────────────────────────────────────────────────────────────
    ("JA",  "Japón", None),
    ("JE",  "Japón", None),
    ("JF",  "Japón", None),
    ("JG",  "Japón", None),
    ("JH",  "Japón", None),
    ("JI",  "Japón", None),
    ("JJ",  "Japón", None),
    ("JK",  "Japón", None),
    ("JL",  "Japón", None),
    ("JM",  "Japón", None),
    ("JN",  "Japón", None),
    ("JO",  "Japón", None),
    ("JP",  "Japón", None),
    ("JQ",  "Japón", None),
    ("JR",  "Japón", None),
    ("JS",  "Japón", None),
    ("7J",  "Japón", None),
    ("7K",  "Japón", None),
    ("7L",  "Japón", None),
    ("7M",  "Japón", None),
    ("7N",  "Japón", None),
    ("8J",  "Japón", None),
    ("JD",  "Islas Ogasawara (Japón)", None),
    ("HL",  "Corea del Sur", None),
    ("DS",  "Corea del Sur", None),
    ("DT",  "Corea del Sur", None),
    ("6K",  "Corea del Sur", None),
    ("6L",  "Corea del Sur", None),
    ("6M",  "Corea del Sur", None),
    ("6N",  "Corea del Sur", None),
    ("P5",  "Corea del Norte", None),
    ("BY",  "China", None),
    ("BA",  "China", None),
    ("BG",  "China", None),
    ("BH",  "China", None),
    ("BI",  "China", None),
    ("BJ",  "China", None),
    ("BT",  "China", None),
    ("BV",  "Taiwán", None),
    ("BU",  "Taiwán", None),
    ("VR2", "Hong Kong (China)", None),
    ("VR",  "Hong Kong (China)", None),
    ("XX9", "Macao (China)", None),
    ("VU",  "India", None),
    ("AT",  "India", None),
    ("AU",  "India", None),
    ("AV",  "India", None),
    ("VT",  "India", None),
    ("AP",  "Pakistán", None),
    ("HS",  "Tailandia", None),
    ("E2",  "Tailandia", None),
    ("9V",  "Singapur", None),
    ("9M",  "Malasia", None),
    ("9W",  "Malasia", None),
    ("YB",  "Indonesia", None),
    ("YC",  "Indonesia", None),
    ("YD",  "Indonesia", None),
    ("YE",  "Indonesia", None),
    ("YF",  "Indonesia", None),
    ("YG",  "Indonesia", None),
    ("YH",  "Indonesia", None),
    ("4W",  "Timor Oriental", None),
    ("DU",  "Filipinas", None),
    ("4D",  "Filipinas", None),
    ("DW",  "Filipinas", None),
    ("4I",  "Filipinas", None),
    ("XV",  "Vietnam", None),
    ("3W",  "Vietnam", None),
    ("XW",  "Laos", None),
    ("XU",  "Camboya", None),
    ("XZ",  "Myanmar", None),
    ("S2",  "Bangladés", None),
    ("4S",  "Sri Lanka", None),
    ("A5",  "Bután", None),
    ("9N",  "Nepal", None),
    ("T6",  "Afganistán", None),
    # ─── Oceanía ──────────────────────────────────────────────────────────────
    ("VK",  "Australia", None),
    ("AX",  "Australia", None),
    ("VK9X","Isla de Navidad (Australia)", None),
    ("VK9C","Islas Cocos-Keeling (Australia)", None),
    ("ZL",  "Nueva Zelanda", None),
    ("ZK",  "Nueva Zelanda", None),
    ("ZM",  "Nueva Zelanda", None),
    ("T8",  "Palaos", None),
    ("V6",  "Micronesia", None),
    ("5W",  "Samoa", None),
    ("3D2", "Fiyi", None),
    ("T2",  "Tuvalu", None),
    ("T3",  "Kiribati", None),
    ("A3",  "Tonga", None),
    ("H4",  "Islas Salomón", None),
    ("YJ",  "Vanuatu", None),
    ("E5",  "Islas Cook Norte (NZ)", None),
    ("ZK1", "Islas Cook (NZ)", None),
    ("FK",  "Nueva Caledonia (Francia)", None),
    ("FO",  "Polinesia Francesa (Francia)", None),
    ("FW",  "Wallis y Futuna (Francia)", None),
    ("KH3", "Johnston Atoll (EUA)", None),
    ("KH4", "Midway (EUA)", None),
    ("KH9", "Wake Island (EUA)", None),
    # ─── África ───────────────────────────────────────────────────────────────
    ("ZS",  "Sudáfrica", None),
    ("ZR",  "Sudáfrica", None),
    ("ZT",  "Sudáfrica", None),
    ("ZU",  "Sudáfrica", None),
    ("V5",  "Namibia", None),
    ("A2",  "Botsuana", None),
    ("Z2",  "Zimbabue", None),
    ("7Q",  "Malaui", None),
    ("C9",  "Mozambique", None),
    ("3DA", "Suazilandia", None),
    ("7P",  "Lesoto", None),
    ("5R",  "Madagascar", None),
    ("3B",  "Mauricio", None),
    ("S7",  "Seychelles", None),
    ("5H",  "Tanzania", None),
    ("5Z",  "Kenia", None),
    ("5X",  "Uganda", None),
    ("5U",  "Níger", None),
    ("5N",  "Nigeria", None),
    ("9G",  "Ghana", None),
    ("TU",  "Costa de Marfil", None),
    ("TT",  "Chad", None),
    ("9Q",  "R. D. del Congo", None),
    ("9X",  "Ruanda", None),
    ("9I",  "Zambia", None),
    ("9J",  "Zambia", None),
    ("C5",  "Gambia", None),
    ("6W",  "Senegal", None),
    ("EL",  "Liberia", None),
    ("9L",  "Sierra Leona", None),
    ("J5",  "Guinea-Bisáu", None),
    ("3X",  "Guinea", None),
    ("TY",  "Benín", None),
    ("5V",  "Togo", None),
    ("XT",  "Burkina Faso", None),
    ("TZ",  "Malí", None),
    ("5T",  "Mauritania", None),
    ("D4",  "Cabo Verde", None),
    ("S9",  "Santo Tomé y Príncipe", None),
    ("TR",  "Gabón", None),
    ("TJ",  "Camerún", None),
    ("TN",  "Rep. del Congo", None),
    ("TL",  "Rep. Centroafricana", None),
    ("D2",  "Angola", None),
    ("CN",  "Marruecos", None),
    ("7X",  "Argelia", None),
    ("3V",  "Túnez", None),
    ("ST",  "Sudán", None),
    ("SS",  "Sudán", None),
    ("SU",  "Egipto", None),
    ("5A",  "Libia", None),
    ("ET",  "Etiopía", None),
    ("6O",  "Somalia", None),
    ("T5",  "Somalia", None),
    ("J2",  "Yibuti", None),
    ("E3",  "Eritrea", None),
    ("7O",  "Yemen", None),
    ("ST2", "Sudán del Sur", None),
]


def seed_prefijos(db: Session) -> None:
    """Inserta los prefijos solo si la tabla está vacía."""
    if db.query(models.PrefijoPais).count() > 0:
        return
    for prefijo, pais, zona_codigo in PREFIJOS:
        db.add(models.PrefijoPais(prefijo=prefijo, pais=pais, zona_codigo=zona_codigo))
    db.commit()
